### ISSUE TITLE
Create network issue

### ISSUE THREAD

**Issue by chuongntv** [vietstacker/OpenStack-Newton-Scripts#13]
- The create_vm.sh is empty

**Comment by congto** [comment]
@chuongntv : oke em, Anh vừa update lại script nhé.

Để thử script thì em cài đặt lại từ đầu nhé.

**Comment by chuongntv** [comment]
@congto cái script install nova cần sửa lại là "auto_vnc.html" nghe anh

**Comment by vietstack** [comment]
@chuongntv Nhất trí em
