### ISSUE TITLE
Scripts for Horizon (control node) and nova (compute node) missing?

### ISSUE THREAD

**Issue by jomeier** [vietstacker/OpenStack-Newton-Scripts#6]
Hi,

I couldn't find the installation scripts for horizon on the control node and nova on the compute node?

Aren't they required in newton anymore?

Best regards,

Josef

**Comment by hieulq** [comment]
@jomeier we are still working on this, @congto are in charge of this task.
Thanks for your question, will notify you after finishing the work.

**Comment by congto** [comment]
@hieulq yes sir !

@jomeier We are comming soon. In week, My team re-contruct OpenStack Newton script and first release in weekend.

**Comment by vietstack** [comment]
Hi @jomeier !

Can You try new scripts, following quick guide in here
https://github.com/vietstacker/OpenStack-Newton-Scripts/tree/master/OPS-U16

**Comment by chuongntv** [comment]
create_vm.sh in empty

**Comment by itsourcevn** [comment]
Chào Anh,
Anh có thể hỗ trợ phần cài đặt cho **cinder** được không ạ.
Cảm ơn Anh!

**Comment by congto** [comment]
@itsourcevn anh không em nhé. Vào tài liệu của docs.openstack.org đọc thêm đi. Script lọc từ đó ra mà thôi.

**Comment by itsourcevn** [comment]
Thank Anh!
