### ISSUE TITLE
Training CI, bashate 

### ISSUE THREAD

**Issue by congto** [vietstacker/OpenStack-Newton-Scripts#9]
@hieulq: Plz, What is CI, basheate ? Can You training for me and contributor other :

**Comment by hieulq** [comment]
@congto the bashate is OpenStack tool for checking your bash style. If your code do not satisfy all requirements, bashate will throw the error.
The CI is the automatically job running bashate each time you send pull request, push new commits.. 
You can see all your error here if you click into the CI status in your pull requests: https://travis-ci.org/vietstacker/OpenStack-Newton-Scripts/builds/176622388
That's all for training.

**Comment by congto** [comment]
@hieulq:

Rule check đâu ? Nhìn toàn E001, E002 chịu luôn. 

Đề xuất việt hoá thông báo luôn cho hệ thống này.

**Comment by congto** [comment]
Style bash đâu? Gửi cho a vài thông tin đi chứ ?

**Comment by hieulq** [comment]
@congto em đã nói rất nhiều lần, và cũng đi dọn cho anh nhiều lần rồi.
Rule check nó đã giải thích cụ thể ở ngay sau code, anh đọc kỹ đi rồi hãy hỏi.
E002: Tab indents:
E006: Line too long:

**Comment by congto** [comment]
@hieulq c

Đề xuất việt hoá và hỗ trợ người mới.

**Comment by hieulq** [comment]
@congto tool của OpenStack, code lỗi theo chuẩn rồi và cũng giải thích rõ ràng rồi.
Nếu anh thích test tại máy mình thì chạy lệnh bashate *.sh mà xem.
Em không việt hóa, anh đọc có mấy chữ tiếng anh mà cũng lười à?

**Comment by congto** [comment]
Đề xuất cung cấp link tham khảo @hieulq

A tìm mãi ko thấy đâu cả :)

**Comment by hieulq** [comment]
https://pypi.python.org/pypi/bashate/

Log nó đã giải thích cụ thể lỗi thế nào, ở dòng bao nhiêu rồi, em xin anh đọc kỹ đi.

**Comment by congto** [comment]
@hieulq

Đấy, có cái link guide như này thì phải gửi. E hướng dẫn có tâm tí đi, link tường minh như này mà ko gửi luôn ở đầu. -1

**Comment by hieulq** [comment]
@congto đọc kỹ log đi, link kia nó chẳng khác gì cái log đâu
-2
